Feat: "주문 시스템 구현"
LandvibeDev/2022-Backend-SummerCoding pull request #14
Opened 2022-07-20 14:55 UTC by eul97

## 요약
사전 과제인 주문 시스템을 구현해 보았습니다

## 어려웠던점
객체 지향의 원칙과 SOLID를 최대한 적용하려고 해봤는데 작성하고보니 너무 trash네요..

## 코드리뷰받고싶은점
매운맛 리뷰 부탁들입니다

2022-07-20 16:34 UTC, kang-jisu requested changes
을호야 뭔가 멋있게짠거같긴한데 실제로 구현해야되는 내용에 비해서 인터페이스-구현체도그렇고 좀 복잡해져서 당황스럽다 ^__^;; 

전체적으로 service에 있는 메서드들이 entity처리하는로직이랑 출력하는부분이 섞여있는 것 같은데 service에서는 가져오기만하고 출력하는 부분은 main에있는게 맞는거같다는 생각이 들기도합니다 ,,, 

~만약에 너의 의도가 "print"이라는 동작이 스프링같은 구현에서 entity->DTO로 변환하는 과정이라고 생각한거였다면 print용 클래스(DTO클래스)를 만들거나 차라리 entity클래스에 print용 메서드를 만들어서 (entity->Dto변환) entity.print()이런식으로 쓰는게 좋을거같은데 .. 이해되려나 나도 무슨말을 하는지 잘 모르겠다. . .~

그리고 뭔가 AppConfig를 만들어서 구현한부분이 static 쓴 위치나 활용이 좀 잘못된거같은데 나도 헷갈리네 @junghunkang @JuneYoungDo 어서들 확인해봐주시면 좋겠네요 .. 

일단 과제가 넘 쉬운내용이라 이 구조가 복잡해보이긴하는데 좋은설계를 한거니깐,, 빠르게 잘햇넴 시간나면 좀 더 고쳐보길 ..

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/AppConfig.java
> +
싱글톤패턴으로 생성해서 다른데서 쓰려는 의도였다면 `static` 붙여주고 바로 
```java
private static final MenuRepository menuRepository = new MemoryMenuRepository();
```
하는게 맞을거같기도 ,, 지금코드대로하면 그냥 AppConfig를 생성하는 만큼 계속 인스턴스가 생성될듯

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/HomeworkMain.java
> +            String op = bf.readLine();
유저오퍼레이션은 번호로만하고 메뉴는 문자열입력으로한 이유가 따로 있나 ? ? 
사용자가 갑자기 커맨드 입력방식이 달라져서 혼란스러울거같은데

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/HomeworkMain.java
> +                    menuOperation();
굳이 전역으로 selectedUser를 만들어서 menuOperation에서도 selectedUser를 사용할필요가 있으려나?
menuOperation(user)로 전달해주고 사용해도 될 것 같넵

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/repository/impl/MemoryMenuRepository.java
> +    private final static Map<Long, Menu> store = new HashMap<>();
위에는 private static final인데 여기는 private final static이네

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/repository/impl/MemoryMenuRepository.java
> +            if (menu.getName().equals(menuName)) return menu;
지금은 entity클래스에 getter setter밖에 없던데 오히려 getter setter를 좀 덜 쓰고 진짜 필요한 상황에 메서드 만들어서 쓰는게 좋아보입니다
예를들면 menu.getName으로 꺼내서 비교하는거보다 `menu.isSame(menuName)`같이 같은 메뉴인지 확인하는 메시지를 보내는게 어떨지 ~

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/repository/impl/MemoryUserRepository.java
> +    }
findByName이랑 별 차이가 없는거같은데 내부적으로 findByName을 쓰고 null여부에 따라서 true/false를 주는건 어떨지 ? 지금처럼 중복되는 형태이면 27~31 라인이랑 41~45 라인 내부 구현이 바뀔일이 있을때 두개를 계속 바꿔줘야할듯

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/repository/impl/MemoryOrderRepository.java
> +    public List<Order> findAllOrders() {
뭔가 비슷한데 findAllMenu findAllUser findAllOrders 하나만 복수형인건 좀 거슬리넵

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/service/impl/MenuServiceImpl.java
> +    }
어떤 menu에 대한 처리가 아니고 단순 print인데 이게 service클래스에 들어와있을 이유가 있나 싶기도하넴

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/service/impl/OrderServiceImpl.java
> +
뭔가 createOrder에 id나 name 두가지경우 받아서 오버로딩하는건 좋긴한데,, 
이걸위해서 orderService랑 menuRepository가 의존성이 생기는게 ,, 좋은방향인지 모르겠네
그냥 `public void createOrder(User user, Menu menu) `로 받고 createOrder 호출하기 전에 Menu를 미리 가지고있는게 나을지도 모르겠당

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/service/impl/OrderServiceImpl.java
> +        user.order(order);
user.order(order)
order를 order한다 같아서 뭔가 이상해보여
user.order(menu) or user.addOrderList(order) 뭐 이런 뉘앙스가 도 맞지않을까 싶긴한데 ..

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/service/impl/UserServiceImpl.java
> +        }
이런예외처리는 좋네염

2022-07-20 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/AppConfig.java
> +    }
뭔가 각각 객체들을 싱글톤으로 생성하려던 의도가 맞을까..?
나도 좀 헷갈리긴하는데 Main이 아니라 여기서 static으로 선언했어야 하는게 아닐까싶네

2022-07-20 16:40 UTC, eul97 commented on src/main/java/com/landvibe/homework/AppConfig.java
> +
아 싱글톤으로 하려한건 맞는데 static을 안썻네..
시간 맞춰서 올리려고 구조 생각하고 객체관계랑 역할 제대로 설계도 안하고 막 짠거라 수정해서 내일 다시 올려보겠습니다

2022-07-20 16:41 UTC, eul97 commented on src/main/java/com/landvibe/homework/HomeworkMain.java
> +            String op = bf.readLine();
이것도 예시가 메뉴는 문자열입력으로 되어있길래 일단 문자열로 했는데 유저오퍼레이션에서 할때는 예시에 없는거라 숫자로 해도 되겠지 해서 했음...
예시가 예시일뿐 바꿔도 되는거라면 다 번호 입력으로 받아서 하고싶은데

2022-07-20 16:42 UTC, eul97 commented on src/main/java/com/landvibe/homework/HomeworkMain.java
> +                    menuOperation();
넵

2022-07-20 16:42 UTC, eul97 commented on src/main/java/com/landvibe/homework/repository/impl/MemoryMenuRepository.java
> +    private final static Map<Long, Menu> store = new HashMap<>();
ㅋㅋㅋㅋㅋㅋㅋ....수정하겠습니다

2022-07-20 16:42 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/HomeworkMain.java
> +            String op = bf.readLine();
다 번호로해도 갠춘~~통일해버리쟈

2022-07-20 17:08 UTC, eul97 commented on src/main/java/com/landvibe/homework/repository/impl/MemoryUserRepository.java
> +    }
넵

2022-07-20 17:09 UTC, eul97 commented on src/main/java/com/landvibe/homework/repository/impl/MemoryOrderRepository.java
> +    public List<Order> findAllOrders() {
오키오키

2022-07-20 17:10 UTC, eul97 commented on src/main/java/com/landvibe/homework/service/impl/MenuServiceImpl.java
> +    }
DTO로 바꿔서 변환해주는 느낌을 생각했는데 단순 프린트면 메인에서 해줘도 되긴 함,,,

2022-07-20 17:11 UTC, eul97 commented on src/main/java/com/landvibe/homework/service/impl/OrderServiceImpl.java
> +        user.order(order);
addOrder(order) 이런식으로 하는건 어떨까여

2022-07-21 12:12 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/service/impl/MenuServiceImpl.java
> +    }
이대로해도 갠춘ㄱ ㅐㄴ춘

2022-07-27 15:46 UTC, kang-jisu approved these changes

2022-07-31 13:52 UTC, merged