Customer, Menu 파일 분리, Menu 변수 이름 변경, Menu 생성자 this 사용
LandvibeDev/2022-Backend-SummerCoding pull request #7
Opened 2022-07-17 15:35 UTC by kick-sim

## 변경사항
리뷰해주신 내용에 맞춰 Customer과 Menu를 각각 java파일로 분리했습니다
Menu의 필드 이름을 더 유연한 설계를 위해서 변경했습니다
Menu의 생성자에 this를 명시하였습니다
각각의 기능들을 클래스안에 메소드를 만들어 분리하였습니다
## 궁금한점
각각의 기능들을 ChineseRestaurant 클래스안에서 메서드로 분리하면 기능을 파악하기 좋을거 같다고 하셔서 분리했는데
분리하다보니 static메소드와 static 필드를 사용하게 되었습니다. 제가 알기로 static은 객체지향적이지 않다고 알고있습니다.
혹시 static을 사용하지 않고도 분리할 수 있는 방법이 있는지 알고싶습니다!!

2022-07-17 16:47 UTC, kang-jisu requested changes
> 각각의 기능들을 ChineseRestaurant 클래스안에서 메서드로 분리하면 기능을 파악하기 좋을거 같다고 하셔서 분리했는데
분리하다보니 static메소드와 static 필드를 사용하게 되었습니다. 제가 알기로 static은 객체지향적이지 않다고 알고있습니다.
혹시 static을 사용하지 않고도 분리할 수 있는 방법이 있는지 알고싶습니다!!

질문한 부분만 먼저 달아둘게 ~
main함수가 `public static void main`형식으로 만들어져있는데, 이 main함수에서 다른 메서드나 필드를 호출하려니깐 `static`을 써야했을거야
1. static 키워드가 java에서 사용되는 의미 / 메모리구조상에 어떻게 올라가기때문에 장단점이 있는건지(->객체지향적이지 않다고 말한 이유도 여기의 단점에 있겠지)
2. 왜 main함수는 static키워드가 필요할지

이런거를 조금 더 깊게 공부해야 단순히 *어 메서드 분리했더니 빨간줄뜨네 이유알아봤더니 static키워드 붙이라고하네 붙이다보니까 변수랑 필드랑 다 붙여야하네 ㅇ_ㅇ;;* 이렇게 개발안할수있오 ! 

모든 메서드랑 필드에 static을 안붙이려면 진짜로 자바 프로그램을 실행하는 main 함수는 따로 두고(ex:`ChineseRestaurantMain.java`), main클래스의 main함수에서 ChineseRestaurant클래스를 인스턴스로 생성하고, `ChineseRestaurant.play()`나  `ChineseRestaurant.start()` 뭐 이런식으로 메서드를 호출해서 프로그램을 실행할 수 있게 만들면 될거같은데~~  이해가되려낭!! (근데 백준풀때나 이렇게 가벼운 과제정도는 main에 구현하느라고 static 붙이게되는건 어쩔수 없어서 어느정도는 넘어가도 괜찮을거같긴해😝)

모르겠으면 더 물어보고 쪼금 더 바꿔봐! 원래 개발하고있던 브랜치(kick-sim/step2)에 그대로 push하면 이 PR에 밑에 커밋 달릴거얍 


- [static과 객체지향적 관점](https://velog.io/@yyy96/static)
- [정적메소드, 너 써도 될까?](https://tecoble.techcourse.co.kr/post/2020-07-16-static-method)

2022-07-17 17:08 UTC, junghunkang commented
> 각각의 기능들을 ChineseRestaurant 클래스안에서 메서드로 분리하면 기능을 파악하기 좋을거 같다고 하셔서 분리했는데
> 분리하다보니 static메소드와 static 필드를 사용하게 되었습니다. 제가 알기로 static은 객체지향적이지 않다고 알고있습니다.
> 혹시 static을 사용하지 않고도 분리할 수 있는 방법이 있는지 알고싶습니다!!

우선 객체지향적으로 설계하기 위해서는 각 클래스마다의 역할을 명확하게 하고 코드를 짜보는게 좋을듯
예) ChineseRestaurant 클래스를 Main 클래스로 잡았는데 왜 ChineseRestaurant 클래스에서 왜 고객 정보를 가져야하는지??
-> 그러면 ChineseRestaurant 말고 별도의 Main 클래스를 만들고 Main 클래스에서 ChineseRestaurant과 Customer 객체를 생성해서 설계를 하는게 좀 더 깔끔한 프로젝트가 될 것 같다
이런 역할들에 대해 고민해보면 아주 아주 좋을듯

2022-07-18 09:10 UTC, JuneYoungDo commented on src/main/java/com/landvibe/homework/Customer.java
> +    Vector<Integer> orderList = new Vector();
vector 사용 지양해주면 더 좋을듯!

2022-07-18 09:10 UTC, JuneYoungDo commented on src/main/java/com/landvibe/homework/ChineseRestaurant.java
> +    static Menu[] menu = new Menu[5];
자바에서 리스트를 표현하는 많은 방법이 있는데, array와 arrayList의 차이는 알고 쓰는게 좋을거같아
[https://dev-coco.tistory.com/15](url)

추후를 생각했을 때는, 가변적인 arrayList가 더 효율적이지 않을까??

2022-07-19 07:18 UTC, KeonHee commented on src/main/java/com/landvibe/homework/ChineseRestaurant.java
> +    static Menu[] menu = new Menu[5];
길이를 고정 해놓으면 메뉴가 추가될때마다 수정해야할 곳이 많아지겠죠? 귀찮기도 하지만 실수로 하나만 빠뜨려도 큰 버그가 발생합니다.
메뉴 개수가 추가/삭제 되더라도 전체적인 프로그램이 안정적으로 돌아갈 수 있도록 신경쓰면서 개선해보면 좋을 것 같습니다.

2022-07-19 16:34 UTC, kang-jisu reviewed
화이팅화이팅

2022-07-19 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/ChineseRestaurant.java
> +    ArrayList<Menu> menu = new ArrayList<Menu>();
보통 선언부 (왼쪽)에는 ArrayList말고 인터페이스형태로 List로 적어주는게 좋아!!
만약에 LinkedList로 바뀌게되도 오른쪽부분만 변경하면되니깐 ~~ 
그리고 menu가 여러개있으니 이름은 menus같이 복수형이면 더 좋을거같당

2022-07-19 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/ChineseRestaurant.java
> +        menu.add(new Menu());
빈 Menu는 왜 넣은거야 ??

2022-07-19 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/Main.java
> +    }
구조는 잘 잡은거같아~~!! 굿굿 👍
```java
//ChineseRestaurant#open
 orderList(customer.get(0));
```
근데 지금은 restaurant.open 메서드 안에 customer.get(0)하고 심찬희 Customer를 계속 꺼내쓰고있던데 뭔가 여러 고객이 왔을 경우에 처리를 할 수 있겠다!확장성을 고려하고 만들었다기엔 그냥 .get(0)하고 첫번째 인덱스를 꺼내버리는것도 좀 이상해보여!!
이번 과제는 간단하게 리스트말고 그냥 하나의 customer객체로만 가거나, 너가 원하는 방향이 있었다면 customer 리스트에서 손님리스트를 전부 처리하든 0번째로 하드코딩하지 않고 특정 손님만 처리하든 뭔가 다른 구현이 있었으면좋겠네~

2022-07-19 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/Menu.java
> +    Menu(){}
위에 `List <Menu>`에 빈 Menu를 넣은거랑 같이 궁금한건데 
Menu값이 아무것도 안들어오는 이 생성자를 만들어서 쓰일곳이 어디있는걸까 ?_?

2022-07-19 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/ChineseRestaurant.java
printMenuList하고 print한다는 의미를 더 드러내는것도 좋을듯!
그리고 1부터 4까지 반복문 범위를 정해버리면 만약 메뉴가 늘어나면 일일이  4->5,,. 고쳐야할텐데 자료구조를 사용할 때는 정말 변하지 않을 숫자 범위가 있는게 아니라면 size, length 같은 메서드 쓰는게 좋을거같아!!
그냥 
`for ( int i = 0 ; i < menu.size(); i++ ) {}` 아니면 `for ( Menu menu : menus) ` 이런식으로 동적으로 사용할 수 있게 반복문을 이용해보는건 어떨지~~

2022-07-19 16:34 UTC, kang-jisu commented on src/main/java/com/landvibe/homework/ChineseRestaurant.java
> +                }
이부분만 봤을때 이 ` if (!order(customer.get(0))`가 주문을 하면서 메뉴가 존재하는지 확인하는 true/false 처리를 해서 결과로 반환해줬다는게 와닿지가 않네 .... ! 
아예 먼저 해당 메뉴가 있는지, 주문할 수 있는지 여부를 확인한 후에 주문하는건 어떨까!
만약에 처리가 정 어렵다면 그냥 `void order(customer)`를 호출하고 order 내부에서 해당 메뉴가 없을경우에 출력해주는것도 괜찮을 것 같고 !!

2022-07-27 15:44 UTC, kang-jisu approved these changes

2022-07-28 14:33 UTC, merged